
spring:
  #thymeleaf
  thymeleaf:
    cache: false
  #database
  datasource:
    generate-unique-name: false
    name: tacocloud
  cassandra:
    keyspace-name: taco_cloud
    schema-action: recreate
    local-datacenter: datacenter1
    username: tacocloud
    password: tacopass
