spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
