spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id:
